# Регистрация с корректными данными.
POST http://localhost:8080/api/v1/register
Content-Type: application/json

{
    "login": "correctLogin",
    "email": "correctEmail@gmail.com",
    "password": "correctPassword123"
}

###

# Регистрация с некорректными логином.
POST http://localhost:8080/api/v1/register
Content-Type: application/json

{
    "login": "incorrect-login",
    "email": "correctEmail@gmail.com",
    "password": "correctPassword123"
}

###

# Регистрация с некорректным паролем.
POST http://localhost:8080/api/v1/register
Content-Type: application/json

{
    "login": "correctLogin",
    "email": "correctEmail@gmail.com",
    "password": "incorrectPassword"
}

###

# Регистрация с некорректными email.
POST http://localhost:8080/api/v1/register
Content-Type: application/json

{
    "login": "correctLogin",
    "email": "incorrectEmail",
    "password": "correctPassword123"
}

###

# Аутентификация с корректными данными.
POST http://localhost:8080/api/v1/login/tesseract
Content-Type: application/json

{
    "login": "vrazukrantov",
    "password": "qwe123"
}

###

# Аутентификация с некорректным логином.
POST http://localhost:8080/api/v1/login/tesseract
Content-Type: application/json

{
    "login": "vrazukrantov-incorrect",
    "password": "qwe123"
}

###

# Аутентификация с некорректным паролем.
POST http://localhost:8080/api/v1/login/tesseract
Content-Type: application/json

{
    "login": "vrazukrantov",
    "password": "qwe123-incorrect"
}

###

# Корректное изменение пароля.
PUT http://localhost:8080/api/v1/password
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ2cmF6dWtyYW50b3YiLCJpYXQiOjE3MDk0NzU4NTcsImV4cCI6MjAxOTY1MTg1N30.NnZ1kUSrXQTfmYICrsEwBVTHQxLy0Y-X9bW0rptZXWI
Content-Type: application/json

{
    "oldPassword": "qwe123",
    "newPassword": "qwe123"
}

###

# Изменение пароля, когда cтарый пароль не совпадает с тем, что лежит в базе.
PUT http://localhost:8080/api/v1/password
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ2cmF6dWtyYW50b3YiLCJpYXQiOjE3MDk0NzU4NTcsImV4cCI6MjAxOTY1MTg1N30.NnZ1kUSrXQTfmYICrsEwBVTHQxLy0Y-X9bW0rptZXWI
Content-Type: application/json

{
    "oldPassword": "123qwe123",
    "newPassword": "qwe123"
}

###

# Изменение пароля, когда новый пароль некорректный.
PUT http://localhost:8080/api/v1/password
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ2cmF6dWtyYW50b3YiLCJpYXQiOjE3MDk0NzU4NTcsImV4cCI6MjAxOTY1MTg1N30.NnZ1kUSrXQTfmYICrsEwBVTHQxLy0Y-X9bW0rptZXWI
Content-Type: application/json

{
    "oldPassword": "qwe123",
    "newPassword": "a"
}

###
