# Корректные данные
POST http://localhost:8080/api/v1/login/tesseract
Content-Type: application/json

{
  "login": "vrazukrantov",
  "password": "qwe123"
}

###

# Некорректный логин
POST http://localhost:8080/api/v1/login/tesseract
Content-Type: application/json

{
    "login": "vrazukrantov-incorrect",
    "password": "qwe123"
}

###

# Некорректный пароль
POST http://localhost:8080/api/v1/login/tesseract
Content-Type: application/json

{
    "login": "vrazukrantov",
    "password": "qwe123-incorrect"
}

###

# Некорректное тело
POST http://localhost:8080/api/v1/login/tesseract
Content-Type: application/json

{
    "incorrect": "body"
}
