# Поменять пароль - корректно.
PUT http://localhost:8080/api/v1/password
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ2cmF6dWtyYW50b3YiLCJpYXQiOjE3MDE3MTc3MzAsImV4cCI6MTczMzI1MzczMH0.ZKVzF7SmgOHh7sg7nZ5lNDLh_GSezrpVZi8h1B7lcBs
Content-Type: application/json

{
    "oldPassword": "qwe123",
    "newPassword": "qwe123"
}

###

# Старый пароль не совпадает с тем, что лежит в базе.
PUT http://localhost:8080/api/v1/password
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ2cmF6dWtyYW50b3YiLCJpYXQiOjE3MDE3MTc3MzAsImV4cCI6MTczMzI1MzczMH0.ZKVzF7SmgOHh7sg7nZ5lNDLh_GSezrpVZi8h1B7lcBs
Content-Type: application/json

{
    "oldPassword": "123qwe123",
    "newPassword": "qwe123"
}

###

# Новый пароль некорректный.
PUT http://localhost:8080/api/v1/password
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ2cmF6dWtyYW50b3YiLCJpYXQiOjE3MDE3MTc3MzAsImV4cCI6MTczMzI1MzczMH0.ZKVzF7SmgOHh7sg7nZ5lNDLh_GSezrpVZi8h1B7lcBs
Content-Type: application/json

{
    "oldPassword": "qwe123",
    "newPassword": "a"
}

###
