GET http://localhost:8080/api/v1/testAssets
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ2c3BvY2hlcm5pbiIsImlhdCI6MTcwMTcwODE3MiwiZXhwIjoxNzAzMTc5NDAxfQ.-U0gpnOlOoCVGLDQjq4FyIau9O7s_ROzwHn07EyCLes

###

GET http://localhost:8080/api/v1/testUsers
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ2c3BvY2hlcm5pbiIsImlhdCI6MTcwMTcwODE3MiwiZXhwIjoxNzAzMTc5NDAxfQ.-U0gpnOlOoCVGLDQjq4FyIau9O7s_ROzwHn07EyCLes

###

GET http://localhost:8080/api/v1/testDiversifications
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ2c3BvY2hlcm5pbiIsImlhdCI6MTcwMTcwODE3MiwiZXhwIjoxNzAzMTc5NDAxfQ.-U0gpnOlOoCVGLDQjq4FyIau9O7s_ROzwHn07EyCLes

###
