name: Deploy
on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Build and deploy
              uses: easingthemes/ssh-deploy@main
              with:
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                  ARGS: "-rlgoDzvc -i"
                  SOURCE: "dist/"
                  REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
                  REMOTE_USER: ${{ secrets.REMOTE_USER }}
                  REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
                  TARGET: ${{ secrets.REMOTE_TARGET }}
                  EXCLUDE: "/dist/, /node_modules/"
                  SCRIPT_BEFORE: |
                      whoami
                      ls -al
                  SCRIPT_AFTER: |
                      whoami
                      ls -al
                      echo $RSYNC_STDOUT