name: End-to-End tests
on: [push]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '18'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Restore AVD cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-33-x86_64

      - name: Create AVD
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Build backend
        run: |
          cd server
          ./gradlew bootJar

      - name: Run postgres
        uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "server/src/main/resources/docker/database/docker-compose.yml"

      - name: Run backend
        run: java -jar server/build/libs/tesseract-0.0.1-SNAPSHOT.jar &

      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: android/gradlew -p android connectedCheck
