name: Integration tests
on: [ push ]


jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Setup Java
                uses: actions/setup-java@v4
                with:
                    distribution: 'temurin'
                    java-version: '18'

            -   name: Setup Gradle
                uses: gradle/actions/setup-gradle@v3

            -   name: Run postgres
                uses: isbang/compose-action@v1.5.1
                with:
                    compose-file: "server/src/main/resources/docker/database/docker-compose.yml"

            -   name: Run tests
                run: |
                    cd server
                    ./gradlew test
